export const NavigationRoutes = {
  // Principal
  home: "/",
  explorer: "/explorer",
  messages: "/messages",
  favorites: "/favorites",
  wallet: "/wallet",
  dashboard: "/dashboard",
  recompenses: "/recompenses",
  premium: "/premium",

  // Modules
  realestate: "/realestate",
  employment: "/employment",
  transport: "/transport",
  health: "/health",
  payment: "/payment",
  community: "/community",
  delivery: "/delivery",
  agriculture: "/agriculture",
  marketplace: "/marketplace",
  travel: "/travel",
  learning: "/learning",
  events: "/events",
  network: "/network",
  businesshub: "/business",
  legal: "/legal",
  reputation: "/reputation",
  challenges: "/challenges",
  marketplacepro: "/marketplace/pro",
  analytics: "/analytics",
  documents: "/documents",
  agenda: "/agenda",
  referral: "/referral",
  accommodation: "/accommodation",
  food: "/food",
  ads: "/ads",
  urbanism: "/urbanism",
  environment: "/environment",
  cityhabitat: "/city-habitat",
  services: "/services",
  tracking: "/tracking",
  school: "/school",
  church: "/church",
  advertising: "/advertising",
  publicdata: "/public-data",
  publicsecurity: "/public-security",
  map3d: "/map3d",

  // Création
  editor: "/editor",
  studio: "/studio",
  storiescreator: "/stories-creator",
  templates: "/templates",
  revenus: "/revenus",
  boost: "/boost",

  // Voyages
  destinations: "/destinations",
  planner: "/planner",
  traveljournal: "/travel-journal",
  travelbudget: "/travel-budget",
  map: "/map",

  // Compte
  profile: "/profile",
  settings: "/settings",
  notifications: "/notifications",
  privacy: "/privacy",
  securityaccount: "/account/security",
  help: "/help",
  faq: "/faq",
  contact: "/contact",
  terms: "/terms",
  cookies: "/cookies",
  legalnotice: "/legal-notice",
  about: "/about",

  // Admin
  admin: "/admin",
  adminUsers: "/admin/users",
  adminModules: "/admin/modules",
  adminAnalytics: "/admin/analytics",
  adminSecurity: "/admin/security",
  adminData: "/admin/data",
} as const;

export type NavigationRoute =
  (typeof NavigationRoutes)[keyof typeof NavigationRoutes];
