import type { FieldConfig } from "@/core/sdk/types";

export const fields: FieldConfig[] = [
  {
    key: "name",
    label: "Nom",
    type: "text",
    required: true,
    placeholder: "Nom du prestataire",
  },
  {
    key: "specialty",
    label: "Spécialité",
    type: "text",
    required: true,
    placeholder: "Ex: Plomberie, Coiffure...",
  },
  {
    key: "description",
    label: "Description",
    type: "textarea",
    required: true,
    placeholder: "Décrivez votre service...",
  },
  {
    key: "price",
    label: "Prix",
    type: "text",
    required: true,
    placeholder: "Ex: 10 000 FCFA / h",
  },
  {
    key: "currency",
    label: "Devise",
    type: "select",
    required: false,
    options: [
      { label: "USD", value: "USD" },
      { label: "EUR", value: "EUR" },
      { label: "CDF", value: "CDF" },
      { label: "CFA", value: "CFA" },
    ],
  },
  {
    key: "category",
    label: "Catégorie",
    type: "select",
    required: true,
    options: [
      { label: "Dépannage", value: "Dépannage" },
      { label: "Beauté", value: "Beauté" },
      { label: "Livraison", value: "Livraison" },
      { label: "Éducation", value: "Éducation" },
      { label: "Photo", value: "Photo" },
      { label: "Bien-être", value: "Bien-être" },
      { label: "Événementiel", value: "Événementiel" },
      { label: "Autre", value: "Autre" },
    ],
  },
  {
    key: "location",
    label: "Localisation",
    type: "text",
    required: true,
    placeholder: "Ville, quartier...",
  },
  {
    key: "responseTime",
    label: "Temps de réponse",
    type: "text",
    required: true,
    placeholder: "Ex: < 30 min",
  },
  {
    key: "skills",
    label: "Compétences",
    type: "text",
    required: false,
    placeholder: "Ajouter une compétence (séparée par des virgules)",
  },
  {
    key: "imageUrl",
    label: "Photo principale",
    type: "text",
    required: false,
  },
  {
    key: "coverImage",
    label: "Photo de couverture",
    type: "text",
    required: false,
  },
  {
    key: "available",
    label: "Disponible",
    type: "boolean",
    required: false,
  },
  {
    key: "verified",
    label: "Vérifié",
    type: "boolean",
    required: false,
  },
  {
    key: "urgent",
    label: "Urgence 24h",
    type: "boolean",
    required: false,
  },
  {
    key: "experience",
    label: "Expérience",
    type: "text",
    required: false,
    placeholder: "Ex: 5 ans",
  },
  {
    key: "languages",
    label: "Langues",
    type: "text",
    required: false,
    placeholder: "Ex: Français, Anglais",
  },
];
