export type AnnonceType =
  | "immobilier"
  | "automobile"
  | "moto"
  | "camion"
  | "pieces-auto"
  | "telephones"
  | "ordinateurs"
  | "tablettes"
  | "tv"
  | "audio"
  | "gaming"
  | "electromenager"
  | "mode"
  | "chaussures"
  | "beaute"
  | "sante"
  | "sport"
  | "bricolage"
  | "construction"
  | "agriculture"
  | "animaux"
  | "emploi"
  | "services"
  | "formation"
  | "livres"
  | "musique"
  | "art"
  | "collection"
  | "bebes"
  | "maison"
  | "meubles"
  | "decoration"
  | "industrie"
  | "mines"
  | "materiel-pro"
  | "hotellerie"
  | "restaurant"
  | "voyage"
  | "tourisme"
  | "evenements"
  | "divers";

export type AnnonceCondition =
  | "neuf"
  | "comme-neuf"
  | "tres-bon"
  | "bon"
  | "acceptable"
  | "a-renover";

export interface Annonce {
  _id: string;
  type: AnnonceType;
  title: string;
  description: string;
  price?: number;
  currency: string;
  images: string[];
  videos?: string[];
  location?: string;
  latitude?: number;
  longitude?: number;
  condition?: AnnonceCondition;
  tags: string[];
  createdAt: number;
  updatedAt: number;
  ownerId: string;
  ownerName?: string;
  ownerAvatar?: string;
  ownerPhone?: string;
  viewCount: number;
  likeCount: number;
  shareCount: number;
  offerCount: number;
  isPromoted?: boolean;
  isPremium?: boolean;
  promotionEnd?: number;
  isReserved?: boolean;
  isSold?: boolean;
  warrantyMonths?: number;
  deliveryAvailable?: boolean;
  deliveryPrice?: number;
  paymentMethods?: string[];
  negotiable?: boolean;
  minPrice?: number;
  avgRating?: number;
  reviewCount?: number;
}
