// 54 pays africains + quelques autres
export const COUNTRIES = [
  // Afrique
  { code: "+213", label: "Algérie", flag: "🇩🇿", iso: "DZ" },
  { code: "+244", label: "Angola", flag: "🇦🇴", iso: "AO" },
  { code: "+229", label: "Bénin", flag: "🇧🇯", iso: "BJ" },
  { code: "+267", label: "Botswana", flag: "🇧🇼", iso: "BW" },
  { code: "+226", label: "Burkina Faso", flag: "🇧🇫", iso: "BF" },
  { code: "+257", label: "Burundi", flag: "🇧🇮", iso: "BI" },
  { code: "+237", label: "Cameroun", flag: "🇨🇲", iso: "CM" },
  { code: "+238", label: "Cap-Vert", flag: "🇨🇻", iso: "CV" },
  { code: "+236", label: "Rép. Centrafricaine", flag: "🇨🇫", iso: "CF" },
  { code: "+235", label: "Tchad", flag: "🇹🇩", iso: "TD" },
  { code: "+269", label: "Comores", flag: "🇰🇲", iso: "KM" },
  { code: "+242", label: "Congo", flag: "🇨🇬", iso: "CG" },
  { code: "+243", label: "RDC", flag: "🇨🇩", iso: "CD" },
  { code: "+225", label: "Côte d'Ivoire", flag: "🇨🇮", iso: "CI" },
  { code: "+253", label: "Djibouti", flag: "🇩🇯", iso: "DJ" },
  { code: "+20", label: "Égypte", flag: "🇪🇬", iso: "EG" },
  { code: "+240", label: "Guinée équatoriale", flag: "🇬🇶", iso: "GQ" },
  { code: "+291", label: "Érythrée", flag: "🇪🇷", iso: "ER" },
  { code: "+268", label: "Eswatini", flag: "🇸🇿", iso: "SZ" },
  { code: "+251", label: "Éthiopie", flag: "🇪🇹", iso: "ET" },
  { code: "+241", label: "Gabon", flag: "🇬🇦", iso: "GA" },
  { code: "+220", label: "Gambie", flag: "🇬🇲", iso: "GM" },
  { code: "+233", label: "Ghana", flag: "🇬🇭", iso: "GH" },
  { code: "+224", label: "Guinée", flag: "🇬🇳", iso: "GN" },
  { code: "+245", label: "Guinée-Bissau", flag: "🇬🇼", iso: "GW" },
  { code: "+254", label: "Kenya", flag: "🇰🇪", iso: "KE" },
  { code: "+266", label: "Lesotho", flag: "🇱🇸", iso: "LS" },
  { code: "+231", label: "Liberia", flag: "🇱🇷", iso: "LR" },
  { code: "+218", label: "Libye", flag: "🇱🇾", iso: "LY" },
  { code: "+261", label: "Madagascar", flag: "🇲🇬", iso: "MG" },
  { code: "+265", label: "Malawi", flag: "🇲🇼", iso: "MW" },
  { code: "+223", label: "Mali", flag: "🇲🇱", iso: "ML" },
  { code: "+222", label: "Mauritanie", flag: "🇲🇷", iso: "MR" },
  { code: "+230", label: "Maurice", flag: "🇲🇺", iso: "MU" },
  { code: "+212", label: "Maroc", flag: "🇲🇦", iso: "MA" },
  { code: "+258", label: "Mozambique", flag: "🇲🇿", iso: "MZ" },
  { code: "+264", label: "Namibie", flag: "🇳🇦", iso: "NA" },
  { code: "+227", label: "Niger", flag: "🇳🇪", iso: "NE" },
  { code: "+234", label: "Nigeria", flag: "🇳🇬", iso: "NG" },
  { code: "+250", label: "Rwanda", flag: "🇷🇼", iso: "RW" },
  { code: "+239", label: "Sao Tomé", flag: "🇸🇹", iso: "ST" },
  { code: "+221", label: "Sénégal", flag: "🇸🇳", iso: "SN" },
  { code: "+248", label: "Seychelles", flag: "🇸🇨", iso: "SC" },
  { code: "+232", label: "Sierra Leone", flag: "🇸🇱", iso: "SL" },
  { code: "+252", label: "Somalie", flag: "🇸🇴", iso: "SO" },
  { code: "+27", label: "Afrique du Sud", flag: "🇿🇦", iso: "ZA" },
  { code: "+211", label: "Soudan du Sud", flag: "🇸🇸", iso: "SS" },
  { code: "+249", label: "Soudan", flag: "🇸🇩", iso: "SD" },
  { code: "+255", label: "Tanzanie", flag: "🇹🇿", iso: "TZ" },
  { code: "+228", label: "Togo", flag: "🇹🇬", iso: "TG" },
  { code: "+216", label: "Tunisie", flag: "🇹🇳", iso: "TN" },
  { code: "+256", label: "Ouganda", flag: "🇺🇬", iso: "UG" },
  { code: "+260", label: "Zambie", flag: "🇿🇲", iso: "ZM" },
  { code: "+263", label: "Zimbabwe", flag: "🇿🇼", iso: "ZW" },
  // Europe / Amérique du Nord
  { code: "+33", label: "France", flag: "🇫🇷", iso: "FR" },
  { code: "+32", label: "Belgique", flag: "🇧🇪", iso: "BE" },
  { code: "+41", label: "Suisse", flag: "🇨🇭", iso: "CH" },
  { code: "+44", label: "Royaume-Uni", flag: "🇬🇧", iso: "GB" },
  { code: "+49", label: "Allemagne", flag: "🇩🇪", iso: "DE" },
  { code: "+1", label: "États-Unis", flag: "🇺🇸", iso: "US" },
  { code: "+1", label: "Canada", flag: "🇨🇦", iso: "CA" },
] as const;

export type Country = (typeof COUNTRIES)[number];
