// src/features/marketplace/index.ts
export * from "./types";
export * from "./adapter";
export * from "./actions";
export * from "./fields";
export * from "./manifest";
export * from "./register";
export * from "./permissions";
export * from "./metrics";
export * from "./lifecycle";
export * from "./search";
export * from "./placeholders";
export * from "./hooks";

// ⚠️ On réexporte explicitement tous les composants sauf SellerPolicies (pour éviter conflit avec le type)
export {
  ProductCard,
  ProductMiniCard,
  ProductListItem,
  ProductSkeleton,
  ProductHeader,
  ProductGallery,
  Product360Viewer,
  ProductARViewer,
  ProductVideos,
  ProductLive,
  ProductPrice,
  ProductDiscount,
  ProductCoupons,
  ProductFlashSale,
  ProductInstallment,
  ProductLoyalty,
  ProductDescription,
  ProductFeatures,
  ProductSpecifications,
  ProductVariants,
  ProductStock,
  ProductAvailability,
  ProductDimensions,
  ProductDocuments,
  ProductWarranty,
  ProductAuthenticity,
  ProductBundle,
  ProductAccessories,
  FrequentlyBoughtTogether,
  ProductRecommendations,
  ProductSimilar,
  RecentlyViewedProducts,
  ProductReviews,
  ProductReviewStats,
  ProductVideoReviews,
  ProductQuestions,
  ProductCommunity,
  ProductDelivery,
  ProductPickup,
  ProductShipping,
  ProductTracking,
  ProductPayment,
  MobileMoneyPayment,
  CryptoPayment,
  SellerCard,
  SellerHeader,
  SellerStats,
  SellerCertification,
  // SellerPolicies est exclu (disponible via import direct)
  SellerProducts,
  SellerReviews,
  SellerFollowers,
  SellerContact,
  SellerChat,
  SellerCall,
  SellerVideoCall,
  ProductShare,
  ProductWishlist,
  ProductCompare,
  ProductReport,
  QuantitySelector,
  AddToCartButton,
  BuyNowButton,
  StickyPurchaseBar,
  MarketplaceCategories,
  MarketplaceSearchBar,
  AIShoppingAssistant,
  AIPriceAdvisor,
  AISimilarProducts,
  CreateProductSheet,
  EditProductSheet,
  DeleteProductSheet,
  UploadMediaSheet,
  UploadVideoSheet,
  CheckoutSheet,
  CartSheet,
  CouponSheet,
  MarketplaceDashboard,
  MarketplaceAnalytics,
  MarketplaceRevenue,
  MarketplaceOrders,
  MarketplaceInventory,
  MarketplaceInsights,
  ProductActions,
  ProductStories,
  ProductReels,
  ProductLiveChat,
  LimitedStockBanner,
  DailyDeals,
  CouponCarousel,
  DeliveryEstimator,
  DeliveryTimeline,
  DeliveryTrackingMap,
  DeliveryInsurance,
  ReferralRewards,
  RewardPoints,
  Cashback,
  MembershipBenefits,
  SellerBadges,
  SellerPerformance,
  SellerTimeline,
  SellerLocation,
  SellerAbout,
  SellerGuarantees,
  MarketplaceCoupons,
  MarketplaceCustomers,
  MarketplaceMessages,
  MarketplaceReturns,
  MarketplaceInvoices,
  MarketplaceReports,
  PaymentHistory,
  RefundSheet,
  EscrowPayment,
  InvoiceViewer,
  ReceiptViewer,
} from "./components";
