// src/features/sante/constants/countries.ts

export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
  currency: string;
  currencySymbol: string;
}

export const COUNTRIES: Country[] = [
  {
    code: "FR",
    name: "France",
    dialCode: "+33",
    flag: "🇫🇷",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "BE",
    name: "Belgique",
    dialCode: "+32",
    flag: "🇧🇪",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "CH",
    name: "Suisse",
    dialCode: "+41",
    flag: "🇨🇭",
    currency: "CHF",
    currencySymbol: "CHF",
  },
  {
    code: "CA",
    name: "Canada",
    dialCode: "+1",
    flag: "🇨🇦",
    currency: "CAD",
    currencySymbol: "$",
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    dialCode: "+225",
    flag: "🇨🇮",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    code: "SN",
    name: "Sénégal",
    dialCode: "+221",
    flag: "🇸🇳",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    code: "CM",
    name: "Cameroun",
    dialCode: "+237",
    flag: "🇨🇲",
    currency: "XAF",
    currencySymbol: "CFA",
  },
  {
    code: "NG",
    name: "Nigeria",
    dialCode: "+234",
    flag: "🇳🇬",
    currency: "NGN",
    currencySymbol: "₦",
  },
  {
    code: "KE",
    name: "Kenya",
    dialCode: "+254",
    flag: "🇰🇪",
    currency: "KES",
    currencySymbol: "KSh",
  },
  {
    code: "ZA",
    name: "Afrique du Sud",
    dialCode: "+27",
    flag: "🇿🇦",
    currency: "ZAR",
    currencySymbol: "R",
  },
  {
    code: "MA",
    name: "Maroc",
    dialCode: "+212",
    flag: "🇲🇦",
    currency: "MAD",
    currencySymbol: "DH",
  },
  {
    code: "DZ",
    name: "Algérie",
    dialCode: "+213",
    flag: "🇩🇿",
    currency: "DZD",
    currencySymbol: "DA",
  },
  {
    code: "TN",
    name: "Tunisie",
    dialCode: "+216",
    flag: "🇹🇳",
    currency: "TND",
    currencySymbol: "DT",
  },
  {
    code: "EG",
    name: "Égypte",
    dialCode: "+20",
    flag: "🇪🇬",
    currency: "EGP",
    currencySymbol: "E£",
  },
  {
    code: "US",
    name: "États-Unis",
    dialCode: "+1",
    flag: "🇺🇸",
    currency: "USD",
    currencySymbol: "$",
  },
  {
    code: "GB",
    name: "Royaume-Uni",
    dialCode: "+44",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
  },
  {
    code: "DE",
    name: "Allemagne",
    dialCode: "+49",
    flag: "🇩🇪",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "ES",
    name: "Espagne",
    dialCode: "+34",
    flag: "🇪🇸",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "IT",
    name: "Italie",
    dialCode: "+39",
    flag: "🇮🇹",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "PT",
    name: "Portugal",
    dialCode: "+351",
    flag: "🇵🇹",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "NL",
    name: "Pays-Bas",
    dialCode: "+31",
    flag: "🇳🇱",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "SE",
    name: "Suède",
    dialCode: "+46",
    flag: "🇸🇪",
    currency: "SEK",
    currencySymbol: "kr",
  },
  {
    code: "NO",
    name: "Norvège",
    dialCode: "+47",
    flag: "🇳🇴",
    currency: "NOK",
    currencySymbol: "kr",
  },
  {
    code: "DK",
    name: "Danemark",
    dialCode: "+45",
    flag: "🇩🇰",
    currency: "DKK",
    currencySymbol: "kr",
  },
  {
    code: "FI",
    name: "Finlande",
    dialCode: "+358",
    flag: "🇫🇮",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "IE",
    name: "Irlande",
    dialCode: "+353",
    flag: "🇮🇪",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "AT",
    name: "Autriche",
    dialCode: "+43",
    flag: "🇦🇹",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "PL",
    name: "Pologne",
    dialCode: "+48",
    flag: "🇵🇱",
    currency: "PLN",
    currencySymbol: "zł",
  },
  {
    code: "CZ",
    name: "République Tchèque",
    dialCode: "+420",
    flag: "🇨🇿",
    currency: "CZK",
    currencySymbol: "Kč",
  },
  {
    code: "HU",
    name: "Hongrie",
    dialCode: "+36",
    flag: "🇭🇺",
    currency: "HUF",
    currencySymbol: "Ft",
  },
  {
    code: "GR",
    name: "Grèce",
    dialCode: "+30",
    flag: "🇬🇷",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    code: "TR",
    name: "Turquie",
    dialCode: "+90",
    flag: "🇹🇷",
    currency: "TRY",
    currencySymbol: "₺",
  },
  {
    code: "RU",
    name: "Russie",
    dialCode: "+7",
    flag: "🇷🇺",
    currency: "RUB",
    currencySymbol: "₽",
  },
  {
    code: "CN",
    name: "Chine",
    dialCode: "+86",
    flag: "🇨🇳",
    currency: "CNY",
    currencySymbol: "¥",
  },
  {
    code: "JP",
    name: "Japon",
    dialCode: "+81",
    flag: "🇯🇵",
    currency: "JPY",
    currencySymbol: "¥",
  },
  {
    code: "IN",
    name: "Inde",
    dialCode: "+91",
    flag: "🇮🇳",
    currency: "INR",
    currencySymbol: "₹",
  },
  {
    code: "BR",
    name: "Brésil",
    dialCode: "+55",
    flag: "🇧🇷",
    currency: "BRL",
    currencySymbol: "R$",
  },
  {
    code: "MX",
    name: "Mexique",
    dialCode: "+52",
    flag: "🇲🇽",
    currency: "MXN",
    currencySymbol: "$",
  },
  {
    code: "AU",
    name: "Australie",
    dialCode: "+61",
    flag: "🇦🇺",
    currency: "AUD",
    currencySymbol: "$",
  },
  {
    code: "NZ",
    name: "Nouvelle-Zélande",
    dialCode: "+64",
    flag: "🇳🇿",
    currency: "NZD",
    currencySymbol: "$",
  },
  {
    code: "SA",
    name: "Arabie Saoudite",
    dialCode: "+966",
    flag: "🇸🇦",
    currency: "SAR",
    currencySymbol: "﷼",
  },
  {
    code: "AE",
    name: "Émirats Arabes Unis",
    dialCode: "+971",
    flag: "🇦🇪",
    currency: "AED",
    currencySymbol: "د.إ",
  },
  {
    code: "IL",
    name: "Israël",
    dialCode: "+972",
    flag: "🇮🇱",
    currency: "ILS",
    currencySymbol: "₪",
  },
  {
    code: "PK",
    name: "Pakistan",
    dialCode: "+92",
    flag: "🇵🇰",
    currency: "PKR",
    currencySymbol: "₨",
  },
  {
    code: "BD",
    name: "Bangladesh",
    dialCode: "+880",
    flag: "🇧🇩",
    currency: "BDT",
    currencySymbol: "৳",
  },
];

export const COUNTRY_CODES = COUNTRIES.map((c) => c.code);
export const COUNTRY_DIAL_CODES = COUNTRIES.map((c) => c.dialCode);
