import {
  Building2,
  Briefcase,
  Bus,
  Heart,
  Users,
  Package,
  Leaf,
  ShoppingBag,
  Plane,
  BookOpen,
  Calendar,
  Network,
  Scale,
  Star,
  Award,
  Hotel,
  UtensilsCrossed,
  Tag,
  Building,
  Ruler,
  TreePine,
  Home as HomeIcon,
  Wrench,
  MapPin,
  GraduationCap,
  Church,
  Megaphone,
  Database,
  ShieldAlert,
  Box,
  FileText,
  HandHeart,
  BarChart2,
  Wallet,
} from "lucide-react-native";
import type { NavSection } from "../navigation.types";
import { getNavigationColors } from "../theme/colors";

const colors = getNavigationColors("dark");

export const modulesNavigation: NavSection = {
  title: "Modules",
  items: [
    {
      id: "realestate",
      icon: Building2,
      label: "Immobilier",
      color: colors.orange,
    },
    {
      id: "employment",
      icon: Briefcase,
      label: "Jobs / Pro",
      color: colors.primary,
    },
    { id: "transport", icon: Bus, label: "Transport", color: colors.info },
    { id: "health", icon: Heart, label: "Santé", color: colors.danger },
    { id: "payment", icon: Wallet, label: "Paiement", color: colors.success },
    {
      id: "community",
      icon: Users,
      label: "Communauté",
      color: colors.primary,
    },
    { id: "delivery", icon: Package, label: "Livraison", color: colors.orange },
    {
      id: "agriculture",
      icon: Leaf,
      label: "Agriculture",
      color: colors.green,
    },
    {
      id: "marketplace",
      icon: ShoppingBag,
      label: "Boutique",
      color: colors.orange,
    },
    { id: "travel", icon: Plane, label: "Voyages", color: colors.cyan },
    {
      id: "learning",
      icon: BookOpen,
      label: "Apprendre",
      color: colors.warning,
    },
    { id: "events", icon: Calendar, label: "Événements", color: colors.pink },
    { id: "network", icon: Network, label: "Réseau Pro", color: colors.violet },
    {
      id: "businesshub",
      icon: Briefcase,
      label: "Business Hub",
      color: colors.primary,
    },
    { id: "legal", icon: Scale, label: "Juridique", color: colors.violet },
    {
      id: "reputation",
      icon: Star,
      label: "Réputation",
      color: colors.warning,
    },
    { id: "challenges", icon: Award, label: "Défis", color: colors.pink },
    {
      id: "marketplacepro",
      icon: ShoppingBag,
      label: "Marketplace Pro",
      color: colors.orange,
      isNew: true,
    },
    {
      id: "analytics",
      icon: BarChart2,
      label: "Analytics",
      color: colors.success,
      isNew: true,
    },
    { id: "documents", icon: FileText, label: "Documents", color: colors.cyan },
    { id: "agenda", icon: Calendar, label: "Agenda", color: colors.violet },
    {
      id: "referral",
      icon: HandHeart,
      label: "Parrainage",
      color: colors.pink,
    },
    {
      id: "accommodation",
      icon: Hotel,
      label: "Hébergement",
      color: colors.violet,
    },
    {
      id: "food",
      icon: UtensilsCrossed,
      label: "Restauration",
      color: colors.orange,
    },
    { id: "ads", icon: Tag, label: "Annonces", color: colors.warning },
    {
      id: "urbanism",
      icon: Building,
      label: "Urbanisme",
      color: colors.violet,
    },
    {
      id: "environment",
      icon: TreePine,
      label: "Environnement",
      color: colors.green,
    },
    {
      id: "cityhabitat",
      icon: HomeIcon,
      label: "City Habitat",
      color: colors.success,
    },
    { id: "services", icon: Wrench, label: "Services", color: colors.orange },
    { id: "tracking", icon: MapPin, label: "Tracking", color: colors.cyan },
    {
      id: "school",
      icon: GraduationCap,
      label: "École",
      color: colors.primary,
    },
    { id: "church", icon: Church, label: "Église", color: colors.pink },
    {
      id: "advertising",
      icon: Megaphone,
      label: "Publicité",
      color: colors.warning,
    },
    {
      id: "publicdata",
      icon: Database,
      label: "Data Publique",
      color: colors.success,
    },
    {
      id: "publicsecurity",
      icon: ShieldAlert,
      label: "Sécurité Publique",
      color: colors.danger,
    },
    { id: "map3d", icon: Box, label: "Carte 3D", color: colors.primary },
  ],
};
